-- TalkMemory スキーマ / マイグレーション（ステップ2）
-- Supabase の SQL Editor に貼り付けて実行する。
-- 冪等（idempotent）に書いてあるので、既存プロジェクトを「復元」した場合も、
-- 新しく「作り直した」場合も、そのまま流せる。

-- ===== テーブル =====

create table if not exists public.users (
  id uuid primary key,
  created_at timestamptz default now()
);

create table if not exists public.images (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id),
  image_url text,
  created_at timestamptz default now()
);

create table if not exists public.learning_histories (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id),
  image_id bigint references public.images(id),
  input_text text,
  feedback_text text,
  advice_text text,
  score int default 0,
  grammar_points jsonb default '[]'::jsonb,
  alternatives jsonb default '[]'::jsonb,
  learned_at timestamptz default now(),
  is_review boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id),
  image_id bigint references public.images(id),
  created_at timestamptz default now(),
  unique (user_id, image_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  learning_history_id bigint references public.learning_histories(id),
  reviewed_at timestamptz default now()
);

-- ===== 既存テーブルへの列追加（ステップ2で追加した構造化カラム）=====
-- すでに learning_histories がある「復元」ケースのために、不足列を足す。
alter table public.learning_histories add column if not exists score int default 0;
alter table public.learning_histories add column if not exists grammar_points jsonb default '[]'::jsonb;
alter table public.learning_histories add column if not exists alternatives jsonb default '[]'::jsonb;
alter table public.learning_histories add column if not exists learned_at timestamptz default now();
alter table public.learning_histories add column if not exists is_review boolean default false;

-- ===== RLS（ログイン無し・デバイスID方式のため anon に読み書きを許可）=====
-- ポートフォリオ用途のため anon ロールに全操作を許可する割り切り。
alter table public.users enable row level security;
alter table public.images enable row level security;
alter table public.learning_histories enable row level security;
alter table public.favorites enable row level security;
alter table public.reviews enable row level security;

do $$
declare t text;
begin
  foreach t in array array['users','images','learning_histories','favorites','reviews']
  loop
    execute format('drop policy if exists "anon_all" on public.%I', t);
    execute format('create policy "anon_all" on public.%I for all to anon using (true) with check (true)', t);
  end loop;
end $$;
